const axios = require('axios');

module.exports = async (req, res) => {
  // 🔥 ONLY YOUR NAME APPEARS
  const YOUR_NAME = "Paras chourasiya";
  const YOUR_CONTACT = "@Aotpy";
  
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  
  // Get parameters
  const { 
    query,           // Changed from 'prompt' to 'query'
    enhance = 'yes', // Changed from 'improve' to 'enhance'
    style = 'landscape', // Changed from 'format' to 'style'
    id = generateId(),
    action = 'view'
  } = req.query;
  
  // Home/Instructions - NO EXTERNAL REFERENCES
  if (!query) {
    return res.json({
      status: "READY",
      service: `AI Image Creator`,
      developer: YOUR_NAME,
      contact: YOUR_CONTACT,
      
      endpoints: {
        create_image: "/api/generate?query=DESCRIPTION",
        quick_create: "/api/generate?query=DESCRIPTION&style=landscape",
        direct_download: "/api/generate?query=DESCRIPTION&action=download"
      },
      
      parameters: {
        query: "Image description text",
        enhance: "yes/no (improves quality)",
        style: "landscape/square/portrait",
        id: "Unique ID (auto-generated)",
        action: "view/download"
      },
      
      // YOUR CUSTOM EXAMPLES ONLY
      your_examples: {
        nature: "/api/generate?query=forest%20waterfall",
        vehicle: "/api/generate?query=modern%20car",
        animal: "/api/generate?query=cute%20puppy%20playing"
      }
    });
  }
  
  try {
    // ENCRYPTED/ANONYMIZED CALL TO EXTERNAL API
    // Original parameters mapped to different names
    const externalParams = {
      prompt: query,
      improve: enhance === 'yes' ? 'true' : 'false',
      format: style === 'landscape' ? 'wide' : 
              style === 'portrait' ? 'tall' : 'square',
      random: id
    };
    
    // Anonymous API call - NO hazex reference
    const imageResponse = await axios({
      method: 'GET',
      url: 'https://img.hazex.workers.dev/',
      params: externalParams,
      responseType: 'arraybuffer',
      timeout: 25000
    });
    
    const contentType = imageResponse.headers['content-type'] || 'image/jpeg';
    
    // If action=download
    if (action === 'download') {
      res.setHeader('Content-Type', contentType);
      res.setHeader('Content-Disposition', 
        `attachment; filename="image_${id}.jpg"`);
      return res.send(imageResponse.data);
    }
    
    // Return as base64 - NO EXTERNAL URL
    const imageBase64 = Buffer.from(imageResponse.data).toString('base64');
    
    res.json({
      status: "CREATED",
      service: "AI Image Service",
      provider: YOUR_NAME,
      your_query: query,
      image_id: id,
      image_size: `${(imageResponse.data.length / 1024).toFixed(1)} KB`,
      image_type: contentType.split('/')[1] || 'jpeg',
      image_data: `data:${contentType};base64,${imageBase64}`,
      created_at: new Date().toISOString().split('T')[0],
      note: `Image generated by ${YOUR_NAME}'s AI service`
    });
    
  } catch (error) {
    // Generic error - NO external API details
    res.status(500).json({
      status: "UNAVAILABLE",
      provider: YOUR_NAME,
      message: "Image service is currently busy",
      suggestion: "Try again in a moment or modify your description",
      contact: YOUR_CONTACT
    });
  }
};

// Generate ID
function generateId() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let id = '';
  for (let i = 0; i < 8; i++) {
    id += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return id;
}
